# Generated by Django 5.2.1 on 2025-05-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='default-tag', unique=True),
            preserve_default=False,
        ),
    ]
